version: '3'
services:
  database:
    image: "postgres:12.2-alpine"
    env_file:
      - ../configs/postgresql.env
    volumes:
      - ./database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  database-data:
